name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build and package
        run: mvn package

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add test steps here (if needed)

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Deploy
        uses: ./.github/workflows/deploy.yml
